// Code generated by skelc. DO NOT EDIT.

package skeled

type Item struct {
	Id    int    `json:"id"`
	Name  string `json:"name"`
	Price int    `json:"price"`
}

// Clone returns a value-isolated copy of the generated data.
func (v Item) Clone() Item {
	cloned := v
	return cloned
}
