// Code generated by skelc. DO NOT EDIT.

package skeled

import (
	"reflect"

	"go.yorun.ai/vine/core/web"
)

func init() {
	web.Register(_RestDemoWebSpec)
}

var _RestDemoWebSpec = &web.WebSpec{
	Name:              "RestDemoWeb",
	SkelName:          "innate.bedemo.RestDemoWeb",
	Hash:              "1069cb26",
	ServerType:        reflect.TypeFor[RestDemoWebServer](),
	DefaultServerType: reflect.TypeFor[*DefaultRestDemoWebServer](),
}

type RestDemoWebServer interface {
	web.Handler

	mustBeRestDemoWebServer()
}

type DefaultRestDemoWebServer struct {
}

func (*DefaultRestDemoWebServer) Routes(*web.Router) {
	panic("method routes is not implemented")
}

func (*DefaultRestDemoWebServer) mustBeRestDemoWebServer() {}
