// Code generated by skelc. DO NOT EDIT.

package skeled

import (
	"go.yorun.ai/vine/core/meta"
	"go.yorun.ai/vine/core/skel"
)

func init() {
	meta.RegisterActor(meta.ActorSpec{
		Name:     "ClientActor",
		SkelName: "innate.meta.ClientActor",
		Hash:     "7d5e0dc0",
	})
}

type ClientActor struct {
	skel.ActorBase
}

func (ClientActor) Name() string {
	return "ClientActor"
}

func (ClientActor) SkelName() string {
	return "innate.meta.ClientActor"
}

func (ClientActor) Vias() []skel.ActorVia {
	return []skel.ActorVia{
		skel.ActorViaOpenAPI,
	}
}
