// Code generated by skelc. DO NOT EDIT.

package skeled

import "go.yorun.ai/vine/core/skel"

func init() {
	skel.RegisterDomainSchema(_DomainSchema)
}

var _DomainSchema = &skel.DomainSchema{
	Domain: "innate.meta",
	Hash:   "0e141f10",
	Full:   true,
	Generated: &skel.GeneratedInfo{
		CompilerVersion: "v0.19.0",
	},

	Webs: []*skel.WebSchema{
		{
			Name:     "MetaCrudWeb",
			SkelName: "innate.meta.MetaCrudWeb",
			Hash:     "954d131a",
			Audiences: []*skel.ActorAudienceSchema{
				{Name: "ClientActor", SkelName: "innate.meta.ClientActor", Via: skel.ActorViaOpenAPI},
			},
		},
	},

	Actors: []*skel.ActorSchema{
		{
			Name:     "ClientActor",
			SkelName: "innate.meta.ClientActor",
			Hash:     "7d5e0dc0",
			Vias: []skel.ActorVia{
				skel.ActorViaOpenAPI,
			},
			AuthEnabled: false,
			PermEnabled: false,
		},
	},
}
