// Code generated by skelc. DO NOT EDIT.

package skeled

import (
	"reflect"

	"go.yorun.ai/vine/core/web"
)

func init() {
	web.Register(_MetaCrudWebSpec)
}

var _MetaCrudWebSpec = &web.WebSpec{
	Name:              "MetaCrudWeb",
	SkelName:          "innate.meta.MetaCrudWeb",
	Hash:              "954d131a",
	ServerType:        reflect.TypeFor[MetaCrudWebServer](),
	DefaultServerType: reflect.TypeFor[*DefaultMetaCrudWebServer](),
}

type MetaCrudWebServer interface {
	web.Handler

	mustBeMetaCrudWebServer()
}

type DefaultMetaCrudWebServer struct {
}

func (*DefaultMetaCrudWebServer) Routes(*web.Router) {
	panic("method routes is not implemented")
}

func (*DefaultMetaCrudWebServer) mustBeMetaCrudWebServer() {}
