// 来源层 · K1–K41 锚点表（附录：来源清单，均于 2026-08-16 访问；按正文首次引用顺序编号）
// cat: company=厂商一手 · industry=行业/官方 · broker=第三方交叉核验 · kimi=研究整理/本项目
window.SOURCES = [
  { k: "K1", cat: "industry", fact: "Supabase 自托管 community-supported；组件清单（GoTrue/PostgREST/Realtime/Storage/Studio/Kong/Supavisor/Logflare）；备份/PITR、分支、管理 API 为平台专属；discussion #39820", urls: ["https://queryglow.com/blog/supabase-self-hosted"], date: "2026-08-16" },
  { k: "K2", cat: "industry", fact: "Supabase 定价模型：Pro $25/月/组织含 $10 compute credit；compute Micro $10 → 16XL $3,730；磁盘 $0.125/GB、出口 $0.09/GB、MAU 超 100K 后 $0.00325/MAU、PITR $100/月 add-on", urls: ["https://selfhost.dev/blog/supabase-pricing-explained/", "https://omidsaffari.com/blog/supabase-pricing"], date: "2026-08（对照官网核验）" },
  { k: "K3", cat: "industry", fact: "Supabase PG17 镜像弃用 TimescaleDB（PG15 保留至 EOL；官方推荐 pg_partman + 原生分区）", urls: ["https://basekick.net/blog/timescaledb-alternatives-2026", "https://www.supascale.app/blog/timescaledb-for-selfhosted-supabase-time-series-data-guide"], date: "2026-08-16" },
  { k: "K4", cat: "company", fact: "InsForge 自托管最小栈 3 个核心容器（postgres + postgrest + app）；PG15（镜像 v15.13.4 含 pgvector/pg_cron）；PostgREST v12.2.12；Realtime 用 Socket.IO", urls: ["https://docs.insforge.dev/core-concepts/database/overview.md", "https://raw.githubusercontent.com/InsForge/InsForge/main/deploy/docker-compose/docker-compose.yml"], date: "2026-08-16" },
  { k: "K5", cat: "company", fact: "InsForge agent 原语：MCP 工具、CLI JSON 输出、config-as-code、backend branching、insforge diagnose；HN 2026-05 Show HN 62 分；MCPMark 为厂商自测未独立复现", urls: ["https://docs.insforge.dev/mcp-setup.md", "https://docs.insforge.dev/agent-native/overview.md", "HN Algolia story 48181342"], date: "2026-05 / 2026-08-16" },
  { k: "K6", cat: "company", fact: "InsForge GitHub API 实测：12,757 stars / 1,138 forks / 125 open issues / ~2,780 commits / 最新 release v1.5.6；repo 2025-07 创建", urls: ["https://github.com/InsForge/InsForge", "GitHub API /repos/InsForge/InsForge"], date: "2026-08-14" },
  { k: "K7", cat: "company", fact: "InsForge 定价：Free $0（5 万 MAU、闲置 1 周自动暂停）、Pro $25/月（100k MAU、8GB DB、含 $10 Compute 抵扣）、Enterprise 有 SOC2/HIPAA/SSO", urls: ["https://insforge.dev/pricing"], date: "2026-08-16" },
  { k: "K8", cat: "broker", fact: "InsForge 第三方实测：HN 48181342（62 分）；agent-finder 独立实测 7/10；社区正面评价集中在 RLS 默认开启 + MCP sane defaults", urls: ["HN Algolia story 48181342", "https://agent-finder.co/reviews/insforge", "https://www.developersdigest.tech/blog/agent-native-backends-insforge"], date: "2026-05 / 2026-08-16" },
  { k: "K9", cat: "company", fact: "InsForge 密钥回退链：issue #905（已关闭）确认 ENCRYPTION_KEY 未设置时静默回退 JWT_SECRET；#1552 fail-closed 加固仍 open；compose 文件仍有 :-${JWT_SECRET:-dev-secret...} 回退链", urls: ["https://github.com/InsForge/InsForge/issues", "https://raw.githubusercontent.com/InsForge/InsForge/main/deploy/docker-compose/docker-compose.yml"], date: "2026-08-16" },
  { k: "K10", cat: "company", fact: "Nubase 架构：Spring Boot 3.2 + Java 17、Next.js Studio、database-per-project 多租户 PG；/rest/v1/* 为 Java 重写 PostgREST 兼容层；内置 Memory（mem0 兼容）与 AI Gateway；无 Realtime/备份/PITR/HA/SSO", urls: ["https://nubase.ai/features", "https://nubase.ai/docs"], date: "2026-08-16" },
  { k: "K11", cat: "company", fact: "Nubase 仓库事实：约 620 stars / 73 forks / 106 commits / 10 contributors / 5 releases（最新 v0.1.4，2026-06-16）；Java 76.1%；Apache-2.0；2026-06-08 首次开源", urls: ["https://github.com/OtterMind/Nubase"], date: "2026-08-11 / 2026-08-16" },
  { k: "K12", cat: "broker", fact: "Nubase 异常信号：620 stars 但 0 issues、仅 5 PR、4 watchers；skillsllm 安全扫描 3 处 secret-exfiltration 中危提示（PASSED）；Reddit/HN/知乎零实质讨论", urls: ["https://skillsllm.com/skill/nubase", "https://ossinsight.io/analyze/OtterMind/Nubase"], date: "2026-08-16" },
  { k: "K13", cat: "company", fact: "ParadeDB pg_search 0.25.2（Docker tag 同步，文档更新于 2026-08-11）；0.25.0 起 pgvector 为前置依赖；AGPL-3.0", urls: ["https://docs.paradedb.com/deploy/upgrading", "https://github.com/paradedb/paradedb/releases"], date: "2026-08-11 / 2026-08-16" },
  { k: "K14", cat: "company", fact: "pg_analytics 仓库 2025-03-19 归档只读；analytics 能力并入 pg_search 主扩展（0.15.9 changelog，2025-04-02 起弃用）", urls: ["https://github.com/paradedb/pg_analytics", "https://docs.paradedb.com/changelog/0.15.9"], date: "2025-03-19 / 2026-08-16" },
  { k: "K15", cat: "broker", fact: "ParadeDB 公司为 YC S23；最近一轮融资 2025-04 Series A1 $12M；2026 年无新融资/收购公开证据（收购传闻未验证）", urls: ["https://pitchbook.com/profiles/company/534519-73"], date: "2025-04 / 2026-08-16" },
  { k: "K16", cat: "industry", fact: "pg_search 托管支持面收窄：AWS RDS 不支持；Neon 2026-03-19 起对新项目禁用、存量 2026 年 9 月移除，迁移目标 lakebase_text", urls: ["https://neon.com/docs/extensions/pg_search", "https://neon.com/docs/extensions/migrate-pg-search-to-lakebase-text", "https://pgxn.org/dist/pg_search/0.18.5/pg_search/README.html"], date: "2026-03-19 / 2026-08-16" },
  { k: "K17", cat: "company", fact: "TimescaleDB 2.29.1（2026-08-04 发布）；2.29.0 起移除 PostgreSQL 15 支持，仅支持 PG 16/17/18", urls: ["https://github.com/timescale/timescaledb/releases"], date: "2026-08-04" },
  { k: "K18", cat: "company", fact: "TimescaleDB 许可证双轨：Apache-2.0 核心版 + TSL（source-available，含连续聚合/列压/保留策略；自用免费、禁止作为托管 DBaaS 转售）；公司 2025-06 更名 Tiger Data；timescaledb-ha 内置 pgvector/pgvectorscale/pgai", urls: ["https://www.tigerdata.com/legal/licenses", "https://docs.tigerdata.com/about/latest/timescaledb-editions/", "https://github.com/timescale/timescaledb-docker-ha"], date: "2026-08-16" },
  { k: "K19", cat: "kimi", fact: "开源组合栈组件映射与成本：paradedb + postgrest + Authentik + Mercure + MinIO + Traefik；常驻内存 4–6 GB；memweave pytest 7/7 通过；compose YAML 解析通过，容器实机启动未验证", urls: ["/mnt/agents/output/ai-memory-backend/baas/README.md"], date: "2026-08-16" },
  { k: "K20", cat: "kimi", fact: "懒猫私有云 LPK 打包配置与一键部署脚本 baas/lazycat/deploy.sh（lzc-cli 打包安装到盒子）", urls: ["/mnt/agents/output/ai-memory-backend/baas/lazycat/"], date: "2026-08-16" },
  { k: "K21", cat: "kimi", fact: "LPK 三件套（package.yml / lzc-manifest.yml / lzc-build.yml）覆盖 7 服务 + 路由 + TCP 转发；密钥由懒猫 stable_secret 自动生成持久化", urls: ["/mnt/agents/output/ai-memory-backend/baas/lazycat/README.md", "https://developer.lazycat.cloud/app-example-porting.html"], date: "2026-08-16" },
  { k: "K22", cat: "company", fact: "Supabase Free/Pro 档位（2026-08 核验官网）", urls: ["https://supabase.com/pricing"], date: "2026-08-16" },
  { k: "K23", cat: "kimi", fact: "白皮书 §2.4 Tier 1/2/3 分层框架（PocketBase Tier 1、Keycloak/Cerbos/K8s Tier 3），本报告以 2026 事实刷新", urls: ["/mnt/agents/upload/AI_Memory_and_Backend_Alternatives_Whitepaper.md"], date: "2026-08-16" },
  { k: "K24", cat: "kimi", fact: "组合栈成本与容量判断：€22/月 4C8G VPS（Hetzner CX32）可承载 1–10 万日活；常驻内存 4–6 GB", urls: ["/mnt/agents/output/ai-memory-backend/baas/README.md"], date: "2026-08-16" },
  { k: "K25", cat: "company", fact: "Nubase 稚嫩事实：620 stars / v0.1.4 / 2026-06 开源 / 无 Realtime/备份/HA/SSO", urls: ["https://github.com/OtterMind/Nubase", "https://nubase.ai/docs"], date: "2026-08-16" },
  { k: "K26", cat: "industry", fact: "Supabase 自托管 community-supported 定位；PG17 弃用 TimescaleDB 需自建镜像", urls: ["https://queryglow.com/blog/supabase-self-hosted", "https://basekick.net/blog/timescaledb-alternatives-2026"], date: "2026-08-16" },
  { k: "K27", cat: "company", fact: "TimescaleDB TSL 双轨、2.29.1、PG15 支持移除", urls: ["https://www.tigerdata.com/legal/licenses", "https://github.com/timescale/timescaledb/releases"], date: "2026-08-04 / 2026-08-16" },
  { k: "K28", cat: "company", fact: "pg_search 0.25.2 / AGPL-3.0；Neon 禁用；RDS 不支持", urls: ["https://github.com/paradedb/paradedb/releases", "https://neon.com/docs/extensions/pg_search", "https://pgxn.org/dist/pg_search/0.18.5/pg_search/README.html"], date: "2026-08-16" },
  { k: "K29", cat: "company", fact: "自动 API 层组件：PostgREST（PGRST_DB_SCHEMA 暴露 schema、RLS 即安全边界）；pREST（Go 单二进制多库路由）；Hasura（GraphQL 联邦 + console）", urls: ["https://github.com/PostgREST/postgrest", "https://github.com/prest/prest", "https://hasura.io"], date: "2026-08-16" },
  { k: "K30", cat: "kimi", fact: "组合栈 CRUD 形态与成本：Authentik JWT + PostgREST，4C8G VPS €22/月承载中小团队内部系统", urls: ["/mnt/agents/output/ai-memory-backend/baas/README.md"], date: "2026-08-16" },
  { k: "K31", cat: "company", fact: "搜索阶梯事实：tsvector 为 Neon 指定降级目标（lakebase_text）；pg_search 0.25.2（BM25 + 向量混合；shared_preload_libraries 重启；RDS 不支持、Neon 禁用）；pg_analytics 归档", urls: ["https://docs.paradedb.com/deploy/upgrading", "https://neon.com/docs/extensions/migrate-pg-search-to-lakebase-text", "https://pgxn.org/dist/pg_search/0.18.5/pg_search/README.html"], date: "2026-08-16" },
  { k: "K32", cat: "company", fact: "金融场景事实：TimescaleDB 连续聚合/列压属 TSL；>10 万行/秒或 TB 级亚秒聚合触发 ClickHouse/kdb+", urls: ["https://www.tigerdata.com/docs/get-started/news/new", "https://www.tigerdata.com/legal/licenses"], date: "2026-08-16" },
  { k: "K33", cat: "company", fact: "timescaledb-ha 镜像内置 pgvector/pgvectorscale/pgai；pgai vectorizer 行插入即自动 embedding", urls: ["https://github.com/timescale/timescaledb-docker-ha"], date: "2026-08-16" },
  { k: "K34", cat: "kimi", fact: "memweave 参考实现：FTS5 BM25 + 向量混合搜索、时间衰减 0.95^days × (1+0.1·access_count)、MMR λ=0.7、WAL 多 Agent 并发、Markdown 真相源、pytest 7/7 通过", urls: ["/mnt/agents/output/ai-memory-backend/memweave/README.md"], date: "2026-08-16" },
  { k: "K35", cat: "industry", fact: "DuckDB SQLite/Postgres 扩展 ATTACH 用法（跨库联邦查询胶水）", urls: ["https://duckdb.org"], date: "2026-08-16" },
  { k: "K36", cat: "kimi", fact: "白皮书第一部分：SQLite 记忆层架构、mem0 对比表、CRDT 同步、「记忆逻辑层 100–200 行 Python 自行实现」结论", urls: ["/mnt/agents/upload/AI_Memory_and_Backend_Alternatives_Whitepaper.md"], date: "2026-08-16" },
  { k: "K37", cat: "kimi", fact: "本报告 §2.4（pg_search 混合搜索）与 §2.6（组合栈参照与 memweave 衔接）", urls: ["/mnt/agents/output/pg-backend-comparison_sec02.md"], date: "2026-08-16" },
  { k: "K38", cat: "broker", fact: "Nubase 安全扫描记录：3 处 secret-exfiltration 中危提示（状态 PASSED）；0 issues / 620 stars 交叉核验", urls: ["https://skillsllm.com/skill/nubase", "https://github.com/OtterMind/Nubase", "https://ossinsight.io/analyze/OtterMind/Nubase"], date: "2026-08-16" },
  { k: "K39", cat: "industry", fact: "Supabase 计量项清单与平台专属功能（磁盘/出口/MAU/PITR）", urls: ["https://selfhost.dev/blog/supabase-pricing-explained/", "https://queryglow.com/blog/supabase-self-hosted"], date: "2026-08-16" },
  { k: "K40", cat: "company", fact: "pg_search AGPL-3.0 网络条款义务；AWS RDS 不支持声明", urls: ["https://docs.paradedb.com/deploy/self-hosted/extension", "https://pgxn.org/dist/pg_search/0.18.5/pg_search/README.html"], date: "2026-08-16" },
  { k: "K41", cat: "company", fact: "Neon 弃用 pg_search 事件：2026-03-19 起新项目禁用、存量 2026 年 9 月移除、导向 lakebase_text", urls: ["https://neon.com/docs/extensions/pg_search", "https://neon.com/docs/extensions/migrate-pg-search-to-lakebase-text"], date: "2026-03-19 / 2026-08-16" },
];

// 便捷查询：K 锚 → 来源
window.srcByKey = k => (window.SOURCES || []).find(s => s.k === k);
// drill-down 的来源行文案
window.srcLine = ks => (Array.isArray(ks) ? ks : [ks]).map(k => {
  const s = window.srcByKey(k);
  return s ? `${s.k} · ${s.date}` : k;
}).join("；");
