import type { Agent, KanbanBoardData, KanbanTask } from './types'
import { DEFAULT_COLUMNS } from './state-machine'

export const MOCK_AGENTS: Agent[] = [
  { id: 'agent-data', name: 'DataAgent', initials: 'DA', role: '数据采集与清洗' },
  { id: 'agent-code', name: 'CodeAgent', initials: 'CA', role: '代码生成与评审' },
  { id: 'agent-doc', name: 'DocAgent', initials: 'DO', role: '文档撰写与归档' },
  { id: 'agent-ops', name: 'OpsAgent', initials: 'OA', role: '部署与监控巡检' },
]

const NOW = '2026-08-03T07:00:00.000Z'
const day = 24 * 60 * 60 * 1000
const iso = (offsetDays: number) => new Date(Date.parse(NOW) + offsetDays * day).toISOString()
const due = (offsetDays: number) => iso(offsetDays).slice(0, 10)

export const MOCK_TASKS: KanbanTask[] = [
  {
    id: 'task-101',
    title: '梳理竞品 Agent 编排能力',
    description: '对比主流 Agent 平台的任务编排、审批介入与看板视图能力，输出差异点清单。',
    status: 'backlog',
    priority: 'medium',
    assigneeId: 'agent-doc',
    creator: 'Patrick',
    dueDate: due(7),
    tags: ['调研'],
    blocked: false,
    logSummary: '等待排期，尚未启动。',
    createdAt: iso(-6),
    updatedAt: iso(-6),
    history: [{ id: 'tr-101-1', from: null, to: 'backlog', at: iso(-6) }],
  },
  {
    id: 'task-102',
    title: '定义任务状态机与流转规则',
    description: '明确 backlog / in_progress / in_review / done 四列的准入准出与 WIP 上限。',
    status: 'backlog',
    priority: 'high',
    assigneeId: 'agent-code',
    creator: 'Patrick',
    dueDate: due(5),
    tags: ['设计', '核心'],
    blocked: false,
    logSummary: '等待排期，尚未启动。',
    createdAt: iso(-5),
    updatedAt: iso(-5),
    history: [{ id: 'tr-102-1', from: null, to: 'backlog', at: iso(-5) }],
  },
  {
    id: 'task-103',
    title: '采集近 30 天任务流转数据',
    description: '从现有项目管理系统导出任务状态变更记录，清洗为统一格式。',
    status: 'in_progress',
    priority: 'high',
    assigneeId: 'agent-data',
    creator: 'Patrick',
    dueDate: due(2),
    tags: ['数据'],
    blocked: false,
    logSummary: '已完成 12 个数据源接入，剩余 3 个待授权。',
    createdAt: iso(-4),
    updatedAt: iso(-1),
    history: [
      { id: 'tr-103-1', from: null, to: 'backlog', at: iso(-4) },
      { id: 'tr-103-2', from: 'backlog', to: 'in_progress', at: iso(-2) },
    ],
  },
  {
    id: 'task-104',
    title: '生成看板首版交互稿',
    description: '基于场景规范输出看板布局、卡片信息与拖拽反馈的交互说明。',
    status: 'in_progress',
    priority: 'medium',
    assigneeId: 'agent-doc',
    creator: 'Patrick',
    dueDate: due(3),
    tags: ['设计'],
    blocked: true,
    logSummary: '阻塞：等待产品确认 WIP 上限规则。',
    createdAt: iso(-3),
    updatedAt: iso(-1),
    history: [
      { id: 'tr-104-1', from: null, to: 'backlog', at: iso(-3) },
      { id: 'tr-104-2', from: 'backlog', to: 'in_progress', at: iso(-2) },
    ],
  },
  {
    id: 'task-105',
    title: '实现拖拽流转与乐观更新',
    description: 'dnd-kit 跨列拖拽 + 状态机校验 + toast 反馈，失败自动回滚。',
    status: 'in_review',
    priority: 'urgent',
    assigneeId: 'agent-code',
    creator: 'Patrick',
    dueDate: due(1),
    tags: ['前端', '核心'],
    blocked: false,
    logSummary: '自测通过 24 条用例，待人工验收空列放置手感。',
    createdAt: iso(-8),
    updatedAt: iso(-0.5),
    history: [
      { id: 'tr-105-1', from: null, to: 'backlog', at: iso(-8) },
      { id: 'tr-105-2', from: 'backlog', to: 'in_progress', at: iso(-6) },
      { id: 'tr-105-3', from: 'in_progress', to: 'in_review', at: iso(-0.5) },
    ],
  },
  {
    id: 'task-106',
    title: '输出场景规范文档初稿',
    description: '组件树、页面结构、状态矩阵与验收清单，供评审使用。',
    status: 'in_review',
    priority: 'medium',
    assigneeId: 'agent-doc',
    creator: 'Patrick',
    dueDate: due(2),
    tags: ['文档'],
    blocked: false,
    logSummary: '初稿完成，等待评审意见。',
    createdAt: iso(-7),
    updatedAt: iso(-1),
    history: [
      { id: 'tr-106-1', from: null, to: 'backlog', at: iso(-7) },
      { id: 'tr-106-2', from: 'backlog', to: 'in_progress', at: iso(-5) },
      { id: 'tr-106-3', from: 'in_progress', to: 'in_review', at: iso(-1) },
    ],
  },
  {
    id: 'task-107',
    title: '搭建 monorepo 工程骨架',
    description: 'pnpm workspace：apps/web + packages/kanban-core + packages/kanban-ui。',
    status: 'done',
    priority: 'high',
    assigneeId: 'agent-ops',
    creator: 'Patrick',
    dueDate: due(-1),
    tags: ['工程'],
    blocked: false,
    logSummary: '骨架搭建完成，typecheck 通过。',
    createdAt: iso(-10),
    updatedAt: iso(-2),
    history: [
      { id: 'tr-107-1', from: null, to: 'backlog', at: iso(-10) },
      { id: 'tr-107-2', from: 'backlog', to: 'in_progress', at: iso(-9) },
      { id: 'tr-107-3', from: 'in_progress', to: 'in_review', at: iso(-3) },
      { id: 'tr-107-4', from: 'in_review', to: 'done', at: iso(-2) },
    ],
  },
  {
    id: 'task-108',
    title: '确认看板列定义与默认视图',
    description: '与产品对齐四列定义、默认排序与筛选口径。',
    status: 'done',
    priority: 'low',
    assigneeId: 'agent-doc',
    creator: 'Patrick',
    tags: ['评审'],
    blocked: false,
    logSummary: '评审通过，结论已归档。',
    createdAt: iso(-12),
    updatedAt: iso(-4),
    history: [
      { id: 'tr-108-1', from: null, to: 'backlog', at: iso(-12) },
      { id: 'tr-108-2', from: 'backlog', to: 'in_progress', at: iso(-11) },
      { id: 'tr-108-3', from: 'in_progress', to: 'done', at: iso(-4) },
    ],
  },
]

export function createMockBoardData(): KanbanBoardData {
  return {
    columns: DEFAULT_COLUMNS,
    tasks: MOCK_TASKS,
    agents: MOCK_AGENTS,
  }
}
