// Code generated by skelc. DO NOT EDIT.

package skeled

import "go.yorun.ai/vine/core/skel"

func init() {
	skel.RegisterDomainSchema(_DomainSchema)
}

var _DomainSchema = &skel.DomainSchema{
	Domain: "innate.bedemo",
	Hash:   "d29379dc",
	Full:   true,
	Generated: &skel.GeneratedInfo{
		CompilerVersion: "v0.11.1",
	},

	Data: []*skel.DataSchema{
		{
			Name:     "Item",
			SkelName: "innate.bedemo.Item",

			Hash: "f90ec135",
			Members: []*skel.MemberSchema{
				{
					Name: "id",

					Type: &skel.TypeSchema{
						Kind:   skel.TypeKindScalar,
						Scalar: skel.ScalarInt,
					},
				},
				{
					Name: "name",

					Type: &skel.TypeSchema{
						Kind:   skel.TypeKindScalar,
						Scalar: skel.ScalarString,
					},
				},
				{
					Name: "price",

					Type: &skel.TypeSchema{
						Kind:   skel.TypeKindScalar,
						Scalar: skel.ScalarInt,
					},
				},
			},
		},
	},

	Webs: []*skel.WebSchema{
		{
			Name:     "RestDemoWeb",
			SkelName: "innate.bedemo.RestDemoWeb",

			Hash: "1069cb26",
			Audiences: []*skel.ActorAudienceSchema{
				{Name: "ClientActor", SkelName: "innate.bedemo.ClientActor", Via: skel.ActorViaOpenAPI},
			},
		},
	},

	Actors: []*skel.ActorSchema{
		{
			Name:     "ClientActor",
			SkelName: "innate.bedemo.ClientActor",

			Hash: "2dea494a",
			Vias: []skel.ActorVia{
				skel.ActorViaOpenAPI,
			},
			AuthEnabled: false,
			PermEnabled: false,
		},
	},
}
